// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "softGrey": "rgba(208, 208, 208, 1)",
 "strongGrey": "rgba(89, 89, 89, 1)",
 "warning": "rgba(250, 108, 128, 1)",
 "peach": "rgba(255, 174, 147, 1)",
 "manhattan": "rgba(84, 95, 217, 1)",
 "almostWhite": "rgba(247, 247, 247, 1)",
 "lightGrey": "rgba(239, 239, 239, 1)",
 "midGrey": "rgba(148, 148, 148, 1)",
 "darkGrey": "rgba(49, 49, 49, 1)",
 "almostBlack": "rgba(37, 37, 37, 1)",
 "primaryDark": "rgba(157, 80, 255, 1)",
 "primary": "rgba(97, 0, 255, 1)"
}

export default colors;