// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "fontTitle": "0.75rem",
 "fontSemibold": "0.6875rem",
 "fontRegular": "0.6875rem"
}

export default fontSizes;