// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const shadows = {
 "shaodwBSharp": "0px 0px 5px rgba(0, 0, 0, 0.3)",
 "shaodwBBorder": "0px 0px 5px rgba(0, 0, 0, 0.15)",
 "shaodwBSoft": "0px 0px 10px rgba(0, 0, 0, 0.1)",
 "shaodwBDrop": "0px 0px 20px rgba(0, 0, 0, 0.25)",
 "shaodwWSoft": "0px 0px 10px rgba(255, 255, 255, 0.1)",
 "shaodwWBorder": "0px 0px 5px rgba(255, 255, 255, 0.1)",
 "shaodwWSharp": "0px 0px 5px rgba(255, 255, 255, 0.3)",
 "shaodwWDrop": "0px 0px 20px rgba(255, 255, 255, 0.25)"
}

export default shadows;