// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "tiny": "0.5rem",
 "small": "1rem",
 "medium": "2.5rem",
 "big": "3rem",
 "large": "4rem",
 "huge": "6rem",
 "popup": "13.5rem",
 "panel": "15.5rem"
}

export default spacing;